### ISSUE TITLE
IntegrityError: null value in column "name_en" violates not-null constraint

### ISSUE THREAD

**Issue by gtolivier** [ulule/django-linguist#14]
Hi,

I have almost exactly the same configuration as your example and when I try to save a Category model in the admin I am getting the following issue:
> IntegrityError: null value in column "name_en" violates not-null constraint
> DETAIL:  Failing row contains (3, null, null).

Here is my models.py:
```
class CategoryManager(LinguistManagerMixin, models.Manager):
    pass


class Category(with_metaclass(LinguistMeta, models.Model)):
    name = models.CharField(
        verbose_name=pgettext_lazy('Video category field', 'name'), max_length=255)

    objects = CategoryManager()

    class Meta:
        verbose_name = pgettext_lazy('Video category model', 'category')
        verbose_name_plural = pgettext_lazy('Video category model', 'categories')
        linguist = {
            'identifier': 'myproject_videos_category',
            'fields': ('name', ),
        }

    def __str__(self):
        return self.name

    def __repr__(self):
        return (
            'Category(name=%r)' % (
                self.name))
```

Here is my admin.py:
```
@admin.register(Category)
class CategoryAdmin(TranslatableModelAdmin):
    list_display = ('name', 'languages_column', )
```

Here is the full traceback:

> Traceback (most recent call last):
>   File "/Users/olivier/Documents/PycharmProjects/myproject/lib/python2.7/site-packages/django/core/handlers/exception.py", line 39, in inner
>     response = get_response(request)
>   File "/Users/olivier/Documents/PycharmProjects/myproject/lib/python2.7/site-packages/django/core/handlers/base.py", line 187, in _get_response
>     response = self.process_exception_by_middleware(e, request)
>   File "/Users/olivier/Documents/PycharmProjects/myproject/lib/python2.7/site-packages/django/core/handlers/base.py", line 185, in _get_response
>     response = wrapped_callback(request, *callback_args, **callback_kwargs)
>   File "/Users/olivier/Documents/PycharmProjects/myproject/lib/python2.7/site-packages/django/contrib/admin/options.py", line 544, in wrapper
>     return self.admin_site.admin_view(view)(*args, **kwargs)
>   File "/Users/olivier/Documents/PycharmProjects/myproject/lib/python2.7/site-packages/django/utils/decorators.py", line 149, in _wrapped_view
>     response = view_func(request, *args, **kwargs)
>   File "/Users/olivier/Documents/PycharmProjects/myproject/lib/python2.7/site-packages/django/views/decorators/cache.py", line 57, in _wrapped_view_func
>     response = view_func(request, *args, **kwargs)
>   File "/Users/olivier/Documents/PycharmProjects/myproject/lib/python2.7/site-packages/django/contrib/admin/sites.py", line 211, in inner
>     return view(request, *args, **kwargs)
>   File "/Users/olivier/Documents/PycharmProjects/myproject/lib/python2.7/site-packages/django/contrib/admin/options.py", line 1509, in add_view
>     return self.changeform_view(request, None, form_url, extra_context)
>   File "/Users/olivier/Documents/PycharmProjects/myproject/lib/python2.7/site-packages/django/utils/decorators.py", line 67, in _wrapper
>     return bound_func(*args, **kwargs)
>   File "/Users/olivier/Documents/PycharmProjects/myproject/lib/python2.7/site-packages/django/utils/decorators.py", line 149, in _wrapped_view
>     response = view_func(request, *args, **kwargs)
>   File "/Users/olivier/Documents/PycharmProjects/myproject/lib/python2.7/site-packages/django/utils/decorators.py", line 63, in bound_func
>     return func.__get__(self, type(self))(*args2, **kwargs2)
>   File "/Users/olivier/Documents/PycharmProjects/myproject/lib/python2.7/site-packages/django/utils/decorators.py", line 185, in inner
>     return func(*args, **kwargs)
>   File "/Users/olivier/Documents/PycharmProjects/myproject/lib/python2.7/site-packages/django/contrib/admin/options.py", line 1449, in changeform_view
>     self.save_model(request, new_object, form, not add)
>   File "/Users/olivier/Documents/PycharmProjects/myproject/lib/python2.7/site-packages/django/contrib/admin/options.py", line 1007, in save_model
>     obj.save()
>   File "/Users/olivier/Documents/PycharmProjects/myproject/lib/python2.7/site-packages/linguist/mixins.py", line 407, in save
>     super(ModelMixin, self).save(*args, **kwargs)
>   File "/Users/olivier/Documents/PycharmProjects/myproject/lib/python2.7/site-packages/django/db/models/base.py", line 796, in save
>     force_update=force_update, update_fields=update_fields)
>   File "/Users/olivier/Documents/PycharmProjects/myproject/lib/python2.7/site-packages/django/db/models/base.py", line 824, in save_base
>     updated = self._save_table(raw, cls, force_insert, force_update, using, update_fields)
>   File "/Users/olivier/Documents/PycharmProjects/myproject/lib/python2.7/site-packages/django/db/models/base.py", line 908, in _save_table
>     result = self._do_insert(cls._base_manager, using, fields, update_pk, raw)
>   File "/Users/olivier/Documents/PycharmProjects/myproject/lib/python2.7/site-packages/django/db/models/base.py", line 947, in _do_insert
>     using=using, raw=raw)
>   File "/Users/olivier/Documents/PycharmProjects/myproject/lib/python2.7/site-packages/django/db/models/manager.py", line 85, in manager_method
>     return getattr(self.get_queryset(), name)(*args, **kwargs)
>   File "/Users/olivier/Documents/PycharmProjects/myproject/lib/python2.7/site-packages/django/db/models/query.py", line 1045, in _insert
>     return query.get_compiler(using=using).execute_sql(return_id)
>   File "/Users/olivier/Documents/PycharmProjects/myproject/lib/python2.7/site-packages/django/db/models/sql/compiler.py", line 1054, in execute_sql
>     cursor.execute(sql, params)
>   File "/Users/olivier/Documents/PycharmProjects/myproject/lib/python2.7/site-packages/django/db/backends/utils.py", line 79, in execute
>     return super(CursorDebugWrapper, self).execute(sql, params)
>   File "/Users/olivier/Documents/PycharmProjects/myproject/lib/python2.7/site-packages/django/db/backends/utils.py", line 64, in execute
>     return self.cursor.execute(sql, params)
>   File "/Users/olivier/Documents/PycharmProjects/myproject/lib/python2.7/site-packages/django/db/utils.py", line 94, in __exit__
>     six.reraise(dj_exc_type, dj_exc_value, traceback)
>   File "/Users/olivier/Documents/PycharmProjects/myproject/lib/python2.7/site-packages/django/db/backends/utils.py", line 64, in execute
>     return self.cursor.execute(sql, params)
> IntegrityError: null value in column "name_en" violates not-null constraint
> DETAIL:  Failing row contains (3, null, null).

Do you have any idea how I could solve this?
Please tell me if you need more info.

Thanks a lot,

Olivier

**Comment by gtolivier** [comment]
I should have mentioned that I am using Python 2.7 and Django 1.10.5.

Also the myproject_videos_category table contains name_en and name_fr fields. Is it normal? Shouldn't the translations be stored in the linguist_translation table?

**Comment by c-sonntag** [comment]
Hi, I have the same error with Django2.1 and Python3.6-2. 
I tried with Django's "polls" tutorial project and here is the error in shell mode: 
```
Hip@hip-desktop MSYS /r/WEB/Django2.1-tutorial
$ python ./manage.py shell
Python 3.6.3 (v3.6.3:2c5fed8, Oct  3 2017, 18:11:49) [MSC v.1900 64 bit (AMD64)]
Type 'copyright', 'credits' or 'license' for more information
IPython 6.2.1 -- An enhanced Interactive Python. Type '?' for help.

In [1]: from polls.models import *
   ...: q = Question(question_text="Quoi de neuf ?", pub_date=timezone.now())
   ...: q.save()
   ...:
---------------------------------------------------------------------------
IntegrityError                            Traceback (most recent call last)
C:\Python\Python36-2\lib\site-packages\django\db\backends\utils.py in _execute(self, sql, params, *ignored_wrapper_args)
     84             else:
---> 85                 return self.cursor.execute(sql, params)
     86

C:\Python\Python36-2\lib\site-packages\django\db\backends\sqlite3\base.py in execute(self, query, params)
    295         query = self.convert_query(query)
--> 296         return Database.Cursor.execute(self, query, params)
    297

IntegrityError: NOT NULL constraint failed: polls_question.question_text_fr

The above exception was the direct cause of the following exception:

IntegrityError                            Traceback (most recent call last)
<ipython-input-1-56db1a3ce5ab> in <module>()
      1 from polls.models import *
      2 q = Question(question_text="Quoi de neuf ?", pub_date=timezone.now())
----> 3 q.save()

C:\Python\Python36-2\lib\site-packages\django\db\models\base.py in save(self, force_insert, force_update, using, update_fields)
    715
    716         self.save_base(using=using, force_insert=force_insert,
--> 717                        force_update=force_update, update_fields=update_fields)
    718     save.alters_data = True
    719

C:\Python\Python36-2\lib\site-packages\django\db\models\base.py in save_base(self, raw, force_insert, force_update, using, update_fields)
    745             if not raw:
    746                 self._save_parents(cls, using, update_fields)
--> 747             updated = self._save_table(raw, cls, force_insert, force_update, using, update_fields)
    748         # Store the database on which the object was saved
    749         self._state.db = using

C:\Python\Python36-2\lib\site-packages\linguist\mixins.py in _save_table(self, raw, cls, force_insert, force_update, using, update_fields)
    470             force_update=force_update,
    471             using=using,
--> 472             update_fields=update_fields,
    473         )
    474         self._linguist.decider.objects.save_translations([self])

C:\Python\Python36-2\lib\site-packages\django\db\models\base.py in _save_table(self, raw, cls, force_insert, force_update, using, update_fields)
    828
    829             update_pk = meta.auto_field and not pk_set
--> 830             result = self._do_insert(cls._base_manager, using, fields, update_pk, raw)
    831             if update_pk:
    832                 setattr(self, meta.pk.attname, result)

C:\Python\Python36-2\lib\site-packages\django\db\models\base.py in _do_insert(self, manager, using, fields, update_pk, raw)
    866         """
    867         return manager._insert([self], fields=fields, return_id=update_pk,
--> 868                                using=using, raw=raw)
    869
    870     def delete(self, using=None, keep_parents=False):

C:\Python\Python36-2\lib\site-packages\django\db\models\manager.py in manager_method(self, *args, **kwargs)
     80         def create_method(name, method):
     81             def manager_method(self, *args, **kwargs):
---> 82                 return getattr(self.get_queryset(), name)(*args, **kwargs)
     83             manager_method.__name__ = method.__name__
     84             manager_method.__doc__ = method.__doc__

C:\Python\Python36-2\lib\site-packages\django\db\models\query.py in _insert(self, objs, fields, return_id, raw, using)
   1131         query = sql.InsertQuery(self.model)
   1132         query.insert_values(fields, objs, raw=raw)
-> 1133         return query.get_compiler(using=using).execute_sql(return_id)
   1134     _insert.alters_data = True
   1135     _insert.queryset_only = False

C:\Python\Python36-2\lib\site-packages\django\db\models\sql\compiler.py in execute_sql(self, return_id)
   1283         with self.connection.cursor() as cursor:
   1284             for sql, params in self.as_sql():
-> 1285                 cursor.execute(sql, params)
   1286             if not return_id:
   1287                 return

C:\Python\Python36-2\lib\site-packages\django\db\backends\utils.py in execute(self, sql, params)
     98         start = time()
     99         try:
--> 100             return super().execute(sql, params)
    101         finally:
    102             stop = time()

C:\Python\Python36-2\lib\site-packages\django\db\backends\utils.py in execute(self, sql, params)
     66
     67     def execute(self, sql, params=None):
---> 68         return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
     69
     70     def executemany(self, sql, param_list):

C:\Python\Python36-2\lib\site-packages\django\db\backends\utils.py in _execute_with_wrappers(self, sql, params, many, executor)
     75         for wrapper in reversed(self.db.execute_wrappers):
     76             executor = functools.partial(wrapper, executor)
---> 77         return executor(sql, params, many, context)
     78
     79     def _execute(self, sql, params, *ignored_wrapper_args):

C:\Python\Python36-2\lib\site-packages\django\db\backends\utils.py in _execute(self, sql, params, *ignored_wrapper_args)
     83                 return self.cursor.execute(sql)
     84             else:
---> 85                 return self.cursor.execute(sql, params)
     86
     87     def _executemany(self, sql, param_list, *ignored_wrapper_args):

C:\Python\Python36-2\lib\site-packages\django\db\utils.py in __exit__(self, exc_type, exc_value, traceback)
     87                 if dj_exc_type not in (DataError, IntegrityError):
     88                     self.wrapper.errors_occurred = True
---> 89                 raise dj_exc_value.with_traceback(traceback) from exc_value
     90
     91     def __call__(self, func):

C:\Python\Python36-2\lib\site-packages\django\db\backends\utils.py in _execute(self, sql, params, *ignored_wrapper_args)
     83                 return self.cursor.execute(sql)
     84             else:
---> 85                 return self.cursor.execute(sql, params)
     86
     87     def _executemany(self, sql, param_list, *ignored_wrapper_args):

C:\Python\Python36-2\lib\site-packages\django\db\backends\sqlite3\base.py in execute(self, query, params)
    294             return Database.Cursor.execute(self, query)
    295         query = self.convert_query(query)
--> 296         return Database.Cursor.execute(self, query, params)
    297
    298     def executemany(self, query, param_list):

IntegrityError: NOT NULL constraint failed: polls_question.question_text_fr
```
And that's what "polls/models.py" looks like: 
```py
from django.db import models
from django.utils.six import with_metaclass
from django.utils.translation import ugettext_lazy as _
from linguist.metaclasses import ModelMeta as LinguistMeta

class Question( with_metaclass( LinguistMeta, models.Model ) ) :
  pub_date = models.DateTimeField( 'date published' )
  question_text = models.CharField( max_length = 200 )
  class Meta :
    verbose_name = _( 'question' )
    verbose_name_plural = _( 'questions' )
    linguist = {
      'identifier' : 'question-linguist',
      'fields'     : ('question_text',),
      'default_language' : 'fr',
    }
  def __str__( self ) :
    return self.question_text

class Choice( with_metaclass( LinguistMeta, models.Model ) ) :
  question = models.ForeignKey( Question, on_delete = models.CASCADE )
  votes = models.IntegerField( default = 0 )
  choice_text = models.CharField( max_length = 200 )
  class Meta :
    verbose_name = _( 'choice' )
    verbose_name_plural = _( 'choices' )
    linguist = {
      'identifier' : 'choice-linguist',
      'fields'     : ('choice_text',),
      'default_language' : 'fr',
    }
  def __str__( self ) :
    return self.choice_text
```
And "settings.py" :  
```py
# [...]
INSTALLED_APPS = [
  # [...]
  'linguist',
]
# [...]
LANGUAGE_CODE = 'fr'
LANGUAGES = (
  ('en', _( "English" )),
  ('fr', _( 'French' )),
)
# [...]
```
Looking forward to any fixes.
Thank you for your attention.
