### ISSUE TITLE
makemigrations adds languages to table fields instead use virtual ones

### ISSUE THREAD

**Issue by brovko** [ulule/django-linguist#20]
Hi,
I am trying to use models.py and admin.py from example.
When I try to create a migration:
`python manage.py makemigrations my_app`
I see:
```
Migrations for 'my_app':
  my_app/migrations/0001_initial.py
    - Create model Bookmark
    - Create model BookmarkTranslation
    - Create model Category
    - Create model Post
```
and inside I see for example for Bookmark (same for other tables)
```
('description_en', models.TextField(blank=True)),
('description_ua', models.TextField(blank=True, null=True)),
('description_pl', models.TextField(blank=True, null=True)),
```
I expected to see no `description` fields.
I am using:

- django: 3.0.7
- python: 3.6.8
- django-linguist: 0.5.0

**UPDATED**
It is possible to remove **description_*** fields by hands.

**Comment by thoas** [comment]
we don't use the Django migrations system internally, PR welcome if you want to fix this behavior.
