### ISSUE TITLE
Why not using ContentTypes instead of identifier

### ISSUE THREAD

**Issue by jrief** [ulule/django-linguist#3]
Linguist uses a unique identifier string to distinguish the models for which we have translations.

Django's [ContentType framework](https://docs.djangoproject.com/en/1.7/ref/contrib/contenttypes/) offers such a foreign key right out of the box. Why don't you use that?

**Comment by thoas** [comment]
By experience the content type framework is a pain to maintain, hard to migrate the data when you change your models and not explicit enough.
