### ISSUE TITLE
Translations can't be updated after they have been created

### ISSUE THREAD

**Issue by rsenk330** [ulule/django-linguist#5]
Creating a new object works great. However, when updating an existing object, it just keeps the original translation. This happens both in the django admin and the python shell.

**Create initial post:**
```python
>>> post = Post()
>>> post.activate_language('en')
>>> post.title = 'Hello'
>>> post.save()
>>> post.pk
1
```

**Update post title**
```python
>>> post = Post.objects.get(pk=1)
>>> post.activate_language('en')
>>> post.title
Hello
>>> post.title = 'Hello Again'
>>> post.save()
```

**Title is not changed (should be "Hello Again"):**
```python
>>> post = Post.objects.get(pk=1)
>>> post.activate_language('en')
>>> post.title
Hello
```

I'm using django 1.8 and python 2.7.6. I tried this using 0.1.2 from pypi and master.

Updating the translation directly in the linguist.Translation table works.

**Comment by thoas** [comment]
Hi @rsenk330 

Thank you for the report, we are on it :)

The current master HEAD fix this behavior, we are adding more assertions and a new version will be released on pypi, I will let you know.

**Comment by thoas** [comment]
We have released the **0.1.3** on pypi which fix the issue and add several unittests

**Comment by thoas** [comment]
Thank you again for the report

**Comment by rsenk330** [comment]
@thoas Perfect, the latest version works! Thanks so much for the quick fix. I'm looking forward to messing around with it a bit more today.

**Comment by thoas** [comment]
@rsenk330 don't hesitate, let us know if you have difficulties.

We are still at the early stage of this application, we will have it on production in the next few weeks ;)
